INSERT INTO component_producers (id, name)
VALUES (gen_random_uuid(), 'American Cores Inc.'),
       (gen_random_uuid(), 'EuCores Plc.'),
       (gen_random_uuid(), 'Working Brains Ltd.'),
       (gen_random_uuid(), 'UAIC'),
       (gen_random_uuid(), 'Conventional engines Inc.'),
       (gen_random_uuid(), 'IonEngine Inc.'),
       (gen_random_uuid(), 'PlasmaSource Inc.'),
       (gen_random_uuid(), 'Fresh Air Co.');

INSERT INTO cores (id, cid, name, power_consumption, computation_power, fully_conscious, helm_control, producer_id)
VALUES (gen_random_uuid(), gen_random_uuid(), 'PrideY 1 213h118', 213, 118, false, true,
        (SELECT id FROM component_producers WHERE name = 'American Cores Inc.')),
       (gen_random_uuid(), gen_random_uuid(), 'PrideX 1 410e1000', 410, 1000, false, false,
        (SELECT id FROM component_producers WHERE name = 'American Cores Inc.')),
       (gen_random_uuid(), gen_random_uuid(), 'E-Core Pluto 6 4400F', 440, 670, true, false,
        (SELECT id FROM component_producers WHERE name = 'EuCores Plc.')),
       (gen_random_uuid(), gen_random_uuid(), 'E-Core Pluto 7 5100FH', 512, 710, true, true,
        (SELECT id FROM component_producers WHERE name = 'EuCores Plc.')),
       (gen_random_uuid(), gen_random_uuid(), 'Comrade B-5', 51, 63, false, false,
        (SELECT id FROM component_producers WHERE name = 'Working Brains Ltd.')),
       (gen_random_uuid(), gen_random_uuid(), 'Comrade B-7', 74, 105, false, false,
        (SELECT id FROM component_producers WHERE name = 'Working Brains Ltd.')),
       (gen_random_uuid(), gen_random_uuid(), 'Comrade A-1', 18, 20, false, false,
        (SELECT id FROM component_producers WHERE name = 'Working Brains Ltd.')),
       (gen_random_uuid(), gen_random_uuid(), 'BinaryAI 8/9', 256, 512, true, true,
        (SELECT id FROM component_producers WHERE name = 'UAIC')),
       (gen_random_uuid(), gen_random_uuid(), 'BinaryAI 9/10', 512, 1024, true, true,
        (SELECT id FROM component_producers WHERE name = 'UAIC')),
       (gen_random_uuid(), gen_random_uuid(), 'BinaryAI 11/11', 2048, 2048, true, true,
        (SELECT id FROM component_producers WHERE name = 'UAIC')),
       (gen_random_uuid(), gen_random_uuid(), 'BinaryAI 13/12', 8192, 4096, true, true,
        (SELECT id FROM component_producers WHERE name = 'UAIC'));

INSERT INTO engines (id, cid, name, power_consumption, acceleration, max_speed, producer_id)
VALUES (gen_random_uuid(), gen_random_uuid(), 'Propeller Savior a10s110', 13, 10, 110,
        (SELECT id FROM component_producers WHERE name = 'Conventional engines Inc.')),
       (gen_random_uuid(), gen_random_uuid(), 'Propeller Savior a21s110', 17, 21, 110,
        (SELECT id FROM component_producers WHERE name = 'Conventional engines Inc.')),
       (gen_random_uuid(), gen_random_uuid(), 'Propeller Thruster a21s150', 24, 21, 150,
        (SELECT id FROM component_producers WHERE name = 'Conventional engines Inc.')),
       (gen_random_uuid(), gen_random_uuid(), 'Propeller Thruster a25s155', 30, 25, 155,
        (SELECT id FROM component_producers WHERE name = 'Conventional engines Inc.')),
       (gen_random_uuid(), gen_random_uuid(), 'Propeller Speeder a31s210', 50, 31, 210,
        (SELECT id FROM component_producers WHERE name = 'Conventional engines Inc.')),
       (gen_random_uuid(), gen_random_uuid(), 'Ionizon MS 31', 110, 58, 310,
        (SELECT id FROM component_producers WHERE name = 'IonEngine Inc.')),
       (gen_random_uuid(), gen_random_uuid(), 'Ionizon MS 35', 125, 65, 350,
        (SELECT id FROM component_producers WHERE name = 'IonEngine Inc.')),
       (gen_random_uuid(), gen_random_uuid(), 'Ionizon A 75', 127, 75, 290,
        (SELECT id FROM component_producers WHERE name = 'IonEngine Inc.')),
       (gen_random_uuid(), gen_random_uuid(), 'Ionizon MS 67', 130, 51, 675,
        (SELECT id FROM component_producers WHERE name = 'IonEngine Inc.')),
       (gen_random_uuid(), gen_random_uuid(), 'Flare f9', 1024, 512, 8192,
        (SELECT id FROM component_producers WHERE name = 'PlasmaSource Inc.')),
       (gen_random_uuid(), gen_random_uuid(), 'Flare h10', 1536, 768, 12288,
        (SELECT id FROM component_producers WHERE name = 'PlasmaSource Inc.')),
       (gen_random_uuid(), gen_random_uuid(), 'Flare f10', 2048, 1024, 16384,
        (SELECT id FROM component_producers WHERE name = 'PlasmaSource Inc.')),
       (gen_random_uuid(), gen_random_uuid(), 'Flare f12***', 8192, 4096, 131072,
        (SELECT id FROM component_producers WHERE name = 'PlasmaSource Inc.'));

INSERT INTO life_support_units (id, cid, name, power_consumption, passenger_capacity, producer_id)
VALUES (gen_random_uuid(), gen_random_uuid(), 'Breath Eco 115', 1, 15,
        (SELECT id FROM component_producers WHERE name = 'Fresh Air Co.')),
       (gen_random_uuid(), gen_random_uuid(), 'Breath Eco 575', 5, 75,
        (SELECT id FROM component_producers WHERE name = 'Fresh Air Co.')),
       (gen_random_uuid(), gen_random_uuid(), 'Breath Eco 10150', 10, 150,
        (SELECT id FROM component_producers WHERE name = 'Fresh Air Co.')),
       (gen_random_uuid(), gen_random_uuid(), 'Breath Stable 3030', 30, 300,
        (SELECT id FROM component_producers WHERE name = 'Fresh Air Co.')),
       (gen_random_uuid(), gen_random_uuid(), 'Breath Stable 6575', 65, 750,
        (SELECT id FROM component_producers WHERE name = 'Fresh Air Co.')),
       (gen_random_uuid(), gen_random_uuid(), 'Breath Heave 1715', 175, 1500,
        (SELECT id FROM component_producers WHERE name = 'Fresh Air Co.')),
       (gen_random_uuid(), gen_random_uuid(), 'Breath Heave 4030', 400, 3000,
        (SELECT id FROM component_producers WHERE name = 'Fresh Air Co.')),
       (gen_random_uuid(), gen_random_uuid(), 'Breath Heave 5140', 512, 4096,
        (SELECT id FROM component_producers WHERE name = 'Fresh Air Co.'));

INSERT INTO people (id, birthdate, forename, surname)
VALUES (gen_random_uuid(), '2034-07-03', 'John', 'Birch'),
       (gen_random_uuid(), '2048-09-21', 'Helene', 'Beewax'),
       (gen_random_uuid(), '2041-11-27', 'Adam', 'Rippon'),
       (gen_random_uuid(), '2047-06-03', 'Teresa', 'June'),
       (gen_random_uuid(), '2050-11-17', 'Paul', 'Cascade'),
       (gen_random_uuid(), '2036-02-11', 'Iva', 'Birch'),
       (gen_random_uuid(), '2051-05-01', 'Leopold', 'Turnip'),
       (gen_random_uuid(), '2050-01-01', 'Lucas', 'Tick'),
       (gen_random_uuid(), '2058-04-15', 'Joana', 'Beewax'),
       (gen_random_uuid(), '2053-01-12', 'Jeremy', 'Clark'),
       (gen_random_uuid(), '2050-05-13', 'Lucky', 'Tearbleed'),
       (gen_random_uuid(), '2050-05-13', 'Icky', 'Tearbleed'),
       (gen_random_uuid(), '2057-11-19', 'Ishta', 'Riczaczka'),
       (gen_random_uuid(), '2048-12-23', 'Minnie', 'Mice'),
       (gen_random_uuid(), '2041-07-27', 'Jason', 'Job'),
       (gen_random_uuid(), '2047-03-05', 'Penelope', 'Bixst'),
       (gen_random_uuid(), '2042-01-04', 'Wallace', 'Wale'),
       (gen_random_uuid(), '2036-07-30', 'Ignacio', 'Lores'),
       (gen_random_uuid(), '2060-08-09', 'Lorenzo', 'Putti'),
       (gen_random_uuid(), '2064-03-28', 'Kamila', 'Kopecká'),
       (gen_random_uuid(), '2039-01-18', 'Luana', 'Cavalcanti'),
       (gen_random_uuid(), '2048-02-19', 'Zira', 'Aldrich'),
       (gen_random_uuid(), '2048-02-02', 'Loqua', 'Pinom'),
       (gen_random_uuid(), '2059-04-07', 'Vala', 'Esex');